import { useState,type FormEvent } from 'react'
import { useJarvisVoice } from '../../hooks/useJarvisVoice'
import { useJarvis } from '../../state/JarvisContext'
import { AudioVisualizer } from './AudioVisualizer'
import { MicrophoneStatus } from './MicrophoneStatus'

const hasPicovoiceConfig=Boolean(import.meta.env.VITE_PICOVOICE_ACCESS_KEY&&import.meta.env.VITE_JARVIS_WAKEWORD_MODEL_PATH)
export function VoiceCommandController(){const{state,patch}=useJarvis();const{sendCommand}=useJarvisVoice();const[input,setInput]=useState('')
  const setVoice=async(enabled:boolean)=>{if(enabled){try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(track=>track.stop());localStorage.setItem('jarvis.voiceEnabled','true');patch({voiceEnabled:true,microphonePermission:'granted'})}catch{patch({voiceEnabled:false,microphonePermission:'denied',orbState:'error'})}}else{localStorage.setItem('jarvis.voiceEnabled','false');window.speechSynthesis?.cancel();patch({voiceEnabled:false,microphoneActive:false,orbState:'sleeping'})}}
  const submit=(event:FormEvent)=>{event.preventDefault();const command=input.trim()||state.transcript.trim();if(!command)return;setInput('');void sendCommand(command)}
  const manual=async()=>{if(!state.voiceEnabled)await setVoice(true);patch({orbState:'command-listening',wakeWordEnabled:false});localStorage.setItem('jarvis.wakeWordEnabled','false')}
  return <section className="command-deck glass-panel" aria-label="Voice and command controls"><div className="command-top"><b>COMMAND INTERFACE</b><span><MicrophoneStatus active={state.microphoneActive} permission={state.microphonePermission}/> / {hasPicovoiceConfig?'PORCUPINE READY':'BROWSER FALLBACK'}</span></div><div className="voice-controls"><button className={`voice-button ${state.voiceEnabled?'active':''}`} onClick={()=>void setVoice(!state.voiceEnabled)}>{state.voiceEnabled?'DISABLE VOICE':'ENABLE VOICE'}</button><button className="voice-button manual" onClick={()=>void manual()} aria-label="Start manual command listening">◉</button><button className="voice-button" onClick={()=>{const enabled=!state.wakeWordEnabled;localStorage.setItem('jarvis.wakeWordEnabled',String(enabled));patch({wakeWordEnabled:enabled})}}>WAKE WORD {state.wakeWordEnabled?'ON':'OFF'}</button><AudioVisualizer active={state.microphoneActive}/></div><form className="command-form" onSubmit={submit}><input value={input} onChange={event=>setInput(event.target.value)} placeholder="Type a command or say ‘Jarvis’…" aria-label="Command"/><button className="send-button">TRANSMIT ↗</button></form><p className="transcript">{state.currentResponse||state.interimTranscript||state.transcript||'Awaiting command on secure channel…'}</p>{!hasPicovoiceConfig&&<p className="setup-note">Development fallback active. Add a Picovoice key and custom jarvis.ppn path for production wake detection.</p>}</section>}
